Added a node-gyp.Readme.txt file. Fixed a minor path bug that occurred if you haven't added the trailing / in the environment variable.

diff --git a/tools/node-gyp b/tools/node-gyp
--- a/tools/node-gyp
+++ b/tools/node-gyp
@@ -7,9 +7,9 @@ then
   exit 1 
 else
 	Proper_Node_Dir=1
-	[ -f "${NODE_ROOT}src/node.h" ] || { Proper_Node_Dir=0 && echo "ERROR: node.h was not in ${NODE_ROOT}src/node.h"; }
-	[ -f "${NODE_ROOT}deps/v8/include/v8.h" ] || { Proper_Node_Dir=0 && echo "ERROR: v8.h was not in ${NODE_ROOT}deps/v8/include/v8.h"; }
-	[ -f "${NODE_ROOT}deps/uv/include/uv.h" ] || { Proper_Node_Dir=0 && echo "ERROR: uv.h was not in ${NODE_ROOT}deps/uv/include/uv.h"; }
+	[ -f "${NODE_ROOT}/src/node.h" ] || { Proper_Node_Dir=0 && echo "ERROR: node.h was not in ${NODE_ROOT}/src/node.h"; }
+	[ -f "${NODE_ROOT}/deps/v8/include/v8.h" ] || { Proper_Node_Dir=0 && echo "ERROR: v8.h was not in ${NODE_ROOT}/deps/v8/include/v8.h"; }
+	[ -f "${NODE_ROOT}/deps/uv/include/uv.h" ] || { Proper_Node_Dir=0 && echo "ERROR: uv.h was not in ${NODE_ROOT}/deps/uv/include/uv.h"; }
 	if  [ $Proper_Node_Dir -lt 1 ]
 	then
 		echo "The $NODE_ROOT doesn't seem to be correct"
@@ -29,5 +29,5 @@ fi
 #if we haven't got a gyp file exit
 [ -z "$module_filename" ] && echo "Gyp file not found!" && exit 1
 echo "Generating project"
-${NODE_ROOT}tools/gyp/gyp -f make $module_filename --depth=. -DNODE_ROOT=$NODE_ROOT
+${NODE_ROOT}/tools/gyp/gyp -f make $module_filename --depth=. -DNODE_ROOT=$NODE_ROOT
 
